# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1439, 958)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.name_text = QPlainTextEdit(self.centralwidget)
        self.name_text.setObjectName(u"name_text")
        self.name_text.setGeometry(QRect(70, 10, 591, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 71, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 71, 31))
        self.label_2.setFont(font)
        self.age_text = QPlainTextEdit(self.centralwidget)
        self.age_text.setObjectName(u"age_text")
        self.age_text.setGeometry(QRect(70, 50, 141, 31))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(230, 50, 71, 31))
        self.label_3.setFont(font)
        self.gender_text = QPlainTextEdit(self.centralwidget)
        self.gender_text.setObjectName(u"gender_text")
        self.gender_text.setGeometry(QRect(300, 50, 121, 31))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(440, 50, 71, 31))
        self.label_4.setFont(font)
        self.house_text = QPlainTextEdit(self.centralwidget)
        self.house_text.setObjectName(u"house_text")
        self.house_text.setGeometry(QRect(500, 50, 161, 31))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(180, 90, 231, 31))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(True)
        self.label_5.setFont(font1)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 130, 71, 31))
        self.label_6.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(80, 130, 71, 31))
        self.label_7.setFont(font)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(190, 130, 101, 31))
        self.label_8.setFont(font)
        self.rating_text_1 = QPlainTextEdit(self.centralwidget)
        self.rating_text_1.setObjectName(u"rating_text_1")
        self.rating_text_1.setGeometry(QRect(20, 160, 41, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.rating_text_1.setFont(font2)
        self.rating_text_1.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_1.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 160, 71, 31))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(False)
        self.label_9.setFont(font3)
        self.specialties_text_1 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_1.setObjectName(u"specialties_text_1")
        self.specialties_text_1.setGeometry(QRect(190, 160, 351, 31))
        self.specialties_text_2 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_2.setObjectName(u"specialties_text_2")
        self.specialties_text_2.setGeometry(QRect(190, 190, 351, 31))
        self.rating_text_2 = QPlainTextEdit(self.centralwidget)
        self.rating_text_2.setObjectName(u"rating_text_2")
        self.rating_text_2.setGeometry(QRect(20, 190, 41, 31))
        self.rating_text_2.setFont(font2)
        self.rating_text_2.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_2.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(80, 190, 101, 31))
        self.label_10.setFont(font3)
        self.specialties_text_3 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_3.setObjectName(u"specialties_text_3")
        self.specialties_text_3.setGeometry(QRect(190, 220, 351, 31))
        self.rating_text_3 = QPlainTextEdit(self.centralwidget)
        self.rating_text_3.setObjectName(u"rating_text_3")
        self.rating_text_3.setGeometry(QRect(20, 220, 41, 31))
        self.rating_text_3.setFont(font2)
        self.rating_text_3.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_3.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_4 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_4.setObjectName(u"specialties_text_4")
        self.specialties_text_4.setGeometry(QRect(190, 250, 351, 31))
        self.rating_text_4 = QPlainTextEdit(self.centralwidget)
        self.rating_text_4.setObjectName(u"rating_text_4")
        self.rating_text_4.setGeometry(QRect(20, 250, 41, 31))
        self.rating_text_4.setFont(font2)
        self.rating_text_4.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_4.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(80, 220, 101, 31))
        self.label_11.setFont(font3)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(80, 250, 101, 31))
        self.label_12.setFont(font3)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(80, 280, 101, 31))
        self.label_13.setFont(font3)
        self.rating_text_5 = QPlainTextEdit(self.centralwidget)
        self.rating_text_5.setObjectName(u"rating_text_5")
        self.rating_text_5.setGeometry(QRect(20, 280, 41, 31))
        self.rating_text_5.setFont(font2)
        self.rating_text_5.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_5.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_5 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_5.setObjectName(u"specialties_text_5")
        self.specialties_text_5.setGeometry(QRect(190, 280, 351, 31))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(80, 310, 101, 31))
        self.label_14.setFont(font3)
        self.rating_text_6 = QPlainTextEdit(self.centralwidget)
        self.rating_text_6.setObjectName(u"rating_text_6")
        self.rating_text_6.setGeometry(QRect(20, 310, 41, 31))
        self.rating_text_6.setFont(font2)
        self.rating_text_6.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_6.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_6 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_6.setObjectName(u"specialties_text_6")
        self.specialties_text_6.setGeometry(QRect(190, 310, 351, 31))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(80, 340, 101, 31))
        self.label_15.setFont(font3)
        self.rating_text_7 = QPlainTextEdit(self.centralwidget)
        self.rating_text_7.setObjectName(u"rating_text_7")
        self.rating_text_7.setGeometry(QRect(20, 340, 41, 31))
        self.rating_text_7.setFont(font2)
        self.rating_text_7.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_7.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_7 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_7.setObjectName(u"specialties_text_7")
        self.specialties_text_7.setGeometry(QRect(190, 340, 351, 31))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(80, 370, 101, 31))
        self.label_16.setFont(font3)
        self.rating_text_8 = QPlainTextEdit(self.centralwidget)
        self.rating_text_8.setObjectName(u"rating_text_8")
        self.rating_text_8.setGeometry(QRect(20, 370, 41, 31))
        self.rating_text_8.setFont(font2)
        self.rating_text_8.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_8.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_8 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_8.setObjectName(u"specialties_text_8")
        self.specialties_text_8.setGeometry(QRect(190, 370, 351, 31))
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(80, 400, 101, 31))
        self.label_17.setFont(font3)
        self.rating_text_9 = QPlainTextEdit(self.centralwidget)
        self.rating_text_9.setObjectName(u"rating_text_9")
        self.rating_text_9.setGeometry(QRect(20, 400, 41, 31))
        self.rating_text_9.setFont(font2)
        self.rating_text_9.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_9.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_9 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_9.setObjectName(u"specialties_text_9")
        self.specialties_text_9.setGeometry(QRect(190, 400, 351, 31))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(80, 430, 101, 31))
        self.label_18.setFont(font3)
        self.rating_text_10 = QPlainTextEdit(self.centralwidget)
        self.rating_text_10.setObjectName(u"rating_text_10")
        self.rating_text_10.setGeometry(QRect(20, 430, 41, 31))
        self.rating_text_10.setFont(font2)
        self.rating_text_10.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_10.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_10 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_10.setObjectName(u"specialties_text_10")
        self.specialties_text_10.setGeometry(QRect(190, 430, 351, 31))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(80, 460, 101, 31))
        self.label_19.setFont(font3)
        self.rating_text_11 = QPlainTextEdit(self.centralwidget)
        self.rating_text_11.setObjectName(u"rating_text_11")
        self.rating_text_11.setGeometry(QRect(20, 460, 41, 31))
        self.rating_text_11.setFont(font2)
        self.rating_text_11.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_11.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_11 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_11.setObjectName(u"specialties_text_11")
        self.specialties_text_11.setGeometry(QRect(190, 460, 351, 31))
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(80, 490, 101, 31))
        self.label_20.setFont(font3)
        self.rating_text_12 = QPlainTextEdit(self.centralwidget)
        self.rating_text_12.setObjectName(u"rating_text_12")
        self.rating_text_12.setGeometry(QRect(20, 490, 41, 31))
        self.rating_text_12.setFont(font2)
        self.rating_text_12.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_12.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_12 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_12.setObjectName(u"specialties_text_12")
        self.specialties_text_12.setGeometry(QRect(190, 490, 351, 31))
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(80, 520, 101, 31))
        self.label_21.setFont(font3)
        self.rating_text_13 = QPlainTextEdit(self.centralwidget)
        self.rating_text_13.setObjectName(u"rating_text_13")
        self.rating_text_13.setGeometry(QRect(20, 520, 41, 31))
        self.rating_text_13.setFont(font2)
        self.rating_text_13.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_13.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_13 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_13.setObjectName(u"specialties_text_13")
        self.specialties_text_13.setGeometry(QRect(190, 520, 351, 31))
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(80, 550, 101, 31))
        self.label_22.setFont(font3)
        self.rating_text_14 = QPlainTextEdit(self.centralwidget)
        self.rating_text_14.setObjectName(u"rating_text_14")
        self.rating_text_14.setGeometry(QRect(20, 550, 41, 31))
        self.rating_text_14.setFont(font2)
        self.rating_text_14.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_14.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_14 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_14.setObjectName(u"specialties_text_14")
        self.specialties_text_14.setGeometry(QRect(190, 550, 351, 31))
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(80, 580, 101, 31))
        self.label_23.setFont(font3)
        self.rating_text_15 = QPlainTextEdit(self.centralwidget)
        self.rating_text_15.setObjectName(u"rating_text_15")
        self.rating_text_15.setGeometry(QRect(20, 580, 41, 31))
        self.rating_text_15.setFont(font2)
        self.rating_text_15.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_15.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_15 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_15.setObjectName(u"specialties_text_15")
        self.specialties_text_15.setGeometry(QRect(190, 580, 351, 31))
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(80, 610, 101, 31))
        self.label_24.setFont(font3)
        self.rating_text_16 = QPlainTextEdit(self.centralwidget)
        self.rating_text_16.setObjectName(u"rating_text_16")
        self.rating_text_16.setGeometry(QRect(20, 610, 41, 31))
        self.rating_text_16.setFont(font2)
        self.rating_text_16.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_16.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_16 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_16.setObjectName(u"specialties_text_16")
        self.specialties_text_16.setGeometry(QRect(190, 610, 351, 31))
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(80, 640, 101, 31))
        self.label_25.setFont(font3)
        self.rating_text_17 = QPlainTextEdit(self.centralwidget)
        self.rating_text_17.setObjectName(u"rating_text_17")
        self.rating_text_17.setGeometry(QRect(20, 640, 41, 31))
        self.rating_text_17.setFont(font2)
        self.rating_text_17.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_17.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_17 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_17.setObjectName(u"specialties_text_17")
        self.specialties_text_17.setGeometry(QRect(190, 640, 351, 31))
        self.label_26 = QLabel(self.centralwidget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(80, 670, 101, 31))
        self.label_26.setFont(font3)
        self.rating_text_18 = QPlainTextEdit(self.centralwidget)
        self.rating_text_18.setObjectName(u"rating_text_18")
        self.rating_text_18.setGeometry(QRect(20, 670, 41, 31))
        self.rating_text_18.setFont(font2)
        self.rating_text_18.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rating_text_18.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.specialties_text_18 = QPlainTextEdit(self.centralwidget)
        self.specialties_text_18.setObjectName(u"specialties_text_18")
        self.specialties_text_18.setGeometry(QRect(190, 670, 351, 31))
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(560, 130, 101, 31))
        self.label_27.setFont(font)
        self.label_27.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bonus_dice_text_1 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_1.setObjectName(u"bonus_dice_text_1")
        self.bonus_dice_text_1.setGeometry(QRect(590, 160, 41, 31))
        self.bonus_dice_text_1.setFont(font2)
        self.bonus_dice_text_1.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_1.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_2 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_2.setObjectName(u"bonus_dice_text_2")
        self.bonus_dice_text_2.setGeometry(QRect(590, 190, 41, 31))
        self.bonus_dice_text_2.setFont(font2)
        self.bonus_dice_text_2.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_2.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_3 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_3.setObjectName(u"bonus_dice_text_3")
        self.bonus_dice_text_3.setGeometry(QRect(590, 220, 41, 31))
        self.bonus_dice_text_3.setFont(font2)
        self.bonus_dice_text_3.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_3.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_4 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_4.setObjectName(u"bonus_dice_text_4")
        self.bonus_dice_text_4.setGeometry(QRect(590, 250, 41, 31))
        self.bonus_dice_text_4.setFont(font2)
        self.bonus_dice_text_4.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_4.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_5 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_5.setObjectName(u"bonus_dice_text_5")
        self.bonus_dice_text_5.setGeometry(QRect(590, 280, 41, 31))
        self.bonus_dice_text_5.setFont(font2)
        self.bonus_dice_text_5.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_5.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_6 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_6.setObjectName(u"bonus_dice_text_6")
        self.bonus_dice_text_6.setGeometry(QRect(590, 310, 41, 31))
        self.bonus_dice_text_6.setFont(font2)
        self.bonus_dice_text_6.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_6.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_7 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_7.setObjectName(u"bonus_dice_text_7")
        self.bonus_dice_text_7.setGeometry(QRect(590, 340, 41, 31))
        self.bonus_dice_text_7.setFont(font2)
        self.bonus_dice_text_7.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_7.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_8 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_8.setObjectName(u"bonus_dice_text_8")
        self.bonus_dice_text_8.setGeometry(QRect(590, 370, 41, 31))
        self.bonus_dice_text_8.setFont(font2)
        self.bonus_dice_text_8.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_8.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_9 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_9.setObjectName(u"bonus_dice_text_9")
        self.bonus_dice_text_9.setGeometry(QRect(590, 400, 41, 31))
        self.bonus_dice_text_9.setFont(font2)
        self.bonus_dice_text_9.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_9.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_10 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_10.setObjectName(u"bonus_dice_text_10")
        self.bonus_dice_text_10.setGeometry(QRect(590, 430, 41, 31))
        self.bonus_dice_text_10.setFont(font2)
        self.bonus_dice_text_10.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_10.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_11 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_11.setObjectName(u"bonus_dice_text_11")
        self.bonus_dice_text_11.setGeometry(QRect(590, 460, 41, 31))
        self.bonus_dice_text_11.setFont(font2)
        self.bonus_dice_text_11.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_11.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_12 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_12.setObjectName(u"bonus_dice_text_12")
        self.bonus_dice_text_12.setGeometry(QRect(590, 490, 41, 31))
        self.bonus_dice_text_12.setFont(font2)
        self.bonus_dice_text_12.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_12.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_13 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_13.setObjectName(u"bonus_dice_text_13")
        self.bonus_dice_text_13.setGeometry(QRect(590, 520, 41, 31))
        self.bonus_dice_text_13.setFont(font2)
        self.bonus_dice_text_13.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_13.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_14 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_14.setObjectName(u"bonus_dice_text_14")
        self.bonus_dice_text_14.setGeometry(QRect(590, 550, 41, 31))
        self.bonus_dice_text_14.setFont(font2)
        self.bonus_dice_text_14.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_14.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_15 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_15.setObjectName(u"bonus_dice_text_15")
        self.bonus_dice_text_15.setGeometry(QRect(590, 580, 41, 31))
        self.bonus_dice_text_15.setFont(font2)
        self.bonus_dice_text_15.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_15.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_16 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_16.setObjectName(u"bonus_dice_text_16")
        self.bonus_dice_text_16.setGeometry(QRect(590, 610, 41, 31))
        self.bonus_dice_text_16.setFont(font2)
        self.bonus_dice_text_16.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_16.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_17 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_17.setObjectName(u"bonus_dice_text_17")
        self.bonus_dice_text_17.setGeometry(QRect(590, 640, 41, 31))
        self.bonus_dice_text_17.setFont(font2)
        self.bonus_dice_text_17.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_17.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_18 = QPlainTextEdit(self.centralwidget)
        self.bonus_dice_text_18.setObjectName(u"bonus_dice_text_18")
        self.bonus_dice_text_18.setGeometry(QRect(590, 670, 41, 31))
        self.bonus_dice_text_18.setFont(font2)
        self.bonus_dice_text_18.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.bonus_dice_text_18.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.label_28 = QLabel(self.centralwidget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(670, 130, 101, 31))
        self.label_28.setFont(font)
        self.label_28.setTextFormat(Qt.TextFormat.MarkdownText)
        self.label_28.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_1 = QLabel(self.centralwidget)
        self.total_dice_1.setObjectName(u"total_dice_1")
        self.total_dice_1.setGeometry(QRect(690, 160, 61, 31))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setItalic(False)
        self.total_dice_1.setFont(font4)
        self.total_dice_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_2 = QLabel(self.centralwidget)
        self.total_dice_2.setObjectName(u"total_dice_2")
        self.total_dice_2.setGeometry(QRect(690, 190, 61, 31))
        self.total_dice_2.setFont(font4)
        self.total_dice_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_3 = QLabel(self.centralwidget)
        self.total_dice_3.setObjectName(u"total_dice_3")
        self.total_dice_3.setGeometry(QRect(690, 220, 61, 31))
        self.total_dice_3.setFont(font4)
        self.total_dice_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_4 = QLabel(self.centralwidget)
        self.total_dice_4.setObjectName(u"total_dice_4")
        self.total_dice_4.setGeometry(QRect(690, 250, 61, 31))
        self.total_dice_4.setFont(font4)
        self.total_dice_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_5 = QLabel(self.centralwidget)
        self.total_dice_5.setObjectName(u"total_dice_5")
        self.total_dice_5.setGeometry(QRect(690, 370, 61, 31))
        self.total_dice_5.setFont(font4)
        self.total_dice_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_6 = QLabel(self.centralwidget)
        self.total_dice_6.setObjectName(u"total_dice_6")
        self.total_dice_6.setGeometry(QRect(690, 340, 61, 31))
        self.total_dice_6.setFont(font4)
        self.total_dice_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_7 = QLabel(self.centralwidget)
        self.total_dice_7.setObjectName(u"total_dice_7")
        self.total_dice_7.setGeometry(QRect(690, 280, 61, 31))
        self.total_dice_7.setFont(font4)
        self.total_dice_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_8 = QLabel(self.centralwidget)
        self.total_dice_8.setObjectName(u"total_dice_8")
        self.total_dice_8.setGeometry(QRect(690, 310, 61, 31))
        self.total_dice_8.setFont(font4)
        self.total_dice_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_9 = QLabel(self.centralwidget)
        self.total_dice_9.setObjectName(u"total_dice_9")
        self.total_dice_9.setGeometry(QRect(690, 400, 61, 31))
        self.total_dice_9.setFont(font4)
        self.total_dice_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_10 = QLabel(self.centralwidget)
        self.total_dice_10.setObjectName(u"total_dice_10")
        self.total_dice_10.setGeometry(QRect(690, 520, 61, 31))
        self.total_dice_10.setFont(font4)
        self.total_dice_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_11 = QLabel(self.centralwidget)
        self.total_dice_11.setObjectName(u"total_dice_11")
        self.total_dice_11.setGeometry(QRect(690, 490, 61, 31))
        self.total_dice_11.setFont(font4)
        self.total_dice_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_12 = QLabel(self.centralwidget)
        self.total_dice_12.setObjectName(u"total_dice_12")
        self.total_dice_12.setGeometry(QRect(690, 580, 61, 31))
        self.total_dice_12.setFont(font4)
        self.total_dice_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_13 = QLabel(self.centralwidget)
        self.total_dice_13.setObjectName(u"total_dice_13")
        self.total_dice_13.setGeometry(QRect(690, 640, 61, 31))
        self.total_dice_13.setFont(font4)
        self.total_dice_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_14 = QLabel(self.centralwidget)
        self.total_dice_14.setObjectName(u"total_dice_14")
        self.total_dice_14.setGeometry(QRect(690, 430, 61, 31))
        self.total_dice_14.setFont(font4)
        self.total_dice_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_15 = QLabel(self.centralwidget)
        self.total_dice_15.setObjectName(u"total_dice_15")
        self.total_dice_15.setGeometry(QRect(690, 610, 61, 31))
        self.total_dice_15.setFont(font4)
        self.total_dice_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_16 = QLabel(self.centralwidget)
        self.total_dice_16.setObjectName(u"total_dice_16")
        self.total_dice_16.setGeometry(QRect(690, 550, 61, 31))
        self.total_dice_16.setFont(font4)
        self.total_dice_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_17 = QLabel(self.centralwidget)
        self.total_dice_17.setObjectName(u"total_dice_17")
        self.total_dice_17.setGeometry(QRect(690, 460, 61, 31))
        self.total_dice_17.setFont(font4)
        self.total_dice_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.total_dice_18 = QLabel(self.centralwidget)
        self.total_dice_18.setObjectName(u"total_dice_18")
        self.total_dice_18.setGeometry(QRect(690, 670, 61, 31))
        self.total_dice_18.setFont(font4)
        self.total_dice_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.qualities_text = QPlainTextEdit(self.centralwidget)
        self.qualities_text.setObjectName(u"qualities_text")
        self.qualities_text.setGeometry(QRect(20, 750, 611, 101))
        self.destiny_checkbox_1 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_1.setObjectName(u"destiny_checkbox_1")
        self.destiny_checkbox_1.setGeometry(QRect(220, 860, 16, 31))
        self.destiny_checkbox_1.setIconSize(QSize(64, 64))
        self.destiny_checkbox_1.setChecked(False)
        self.destiny_checkbox_1.setTristate(False)
        self.label_29 = QLabel(self.centralwidget)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(180, 710, 231, 31))
        self.label_29.setFont(font1)
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_30 = QLabel(self.centralwidget)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(60, 860, 131, 31))
        self.label_30.setFont(font)
        self.destiny_checkbox_2 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_2.setObjectName(u"destiny_checkbox_2")
        self.destiny_checkbox_2.setGeometry(QRect(250, 860, 16, 31))
        self.destiny_checkbox_2.setIconSize(QSize(64, 64))
        self.destiny_checkbox_2.setChecked(False)
        self.destiny_checkbox_2.setTristate(False)
        self.destiny_checkbox_4 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_4.setObjectName(u"destiny_checkbox_4")
        self.destiny_checkbox_4.setGeometry(QRect(310, 860, 16, 31))
        self.destiny_checkbox_4.setIconSize(QSize(64, 64))
        self.destiny_checkbox_4.setChecked(False)
        self.destiny_checkbox_4.setTristate(False)
        self.destiny_checkbox_3 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_3.setObjectName(u"destiny_checkbox_3")
        self.destiny_checkbox_3.setGeometry(QRect(280, 860, 16, 31))
        self.destiny_checkbox_3.setIconSize(QSize(64, 64))
        self.destiny_checkbox_3.setChecked(False)
        self.destiny_checkbox_3.setTristate(False)
        self.destiny_checkbox_5 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_5.setObjectName(u"destiny_checkbox_5")
        self.destiny_checkbox_5.setGeometry(QRect(340, 860, 16, 31))
        self.destiny_checkbox_5.setIconSize(QSize(64, 64))
        self.destiny_checkbox_5.setChecked(False)
        self.destiny_checkbox_5.setTristate(False)
        self.destiny_checkbox_6 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_6.setObjectName(u"destiny_checkbox_6")
        self.destiny_checkbox_6.setGeometry(QRect(370, 860, 16, 31))
        self.destiny_checkbox_6.setIconSize(QSize(64, 64))
        self.destiny_checkbox_6.setChecked(False)
        self.destiny_checkbox_6.setTristate(False)
        self.destiny_checkbox_8 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_8.setObjectName(u"destiny_checkbox_8")
        self.destiny_checkbox_8.setGeometry(QRect(430, 860, 16, 31))
        self.destiny_checkbox_8.setIconSize(QSize(64, 64))
        self.destiny_checkbox_8.setChecked(False)
        self.destiny_checkbox_8.setTristate(False)
        self.destiny_checkbox_7 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_7.setObjectName(u"destiny_checkbox_7")
        self.destiny_checkbox_7.setGeometry(QRect(400, 860, 16, 31))
        self.destiny_checkbox_7.setIconSize(QSize(64, 64))
        self.destiny_checkbox_7.setChecked(False)
        self.destiny_checkbox_7.setTristate(False)
        self.destiny_checkbox_9 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_9.setObjectName(u"destiny_checkbox_9")
        self.destiny_checkbox_9.setGeometry(QRect(460, 860, 16, 31))
        self.destiny_checkbox_9.setIconSize(QSize(64, 64))
        self.destiny_checkbox_9.setChecked(False)
        self.destiny_checkbox_9.setTristate(False)
        self.destiny_checkbox_11 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_11.setObjectName(u"destiny_checkbox_11")
        self.destiny_checkbox_11.setGeometry(QRect(520, 860, 16, 31))
        self.destiny_checkbox_11.setIconSize(QSize(64, 64))
        self.destiny_checkbox_11.setChecked(False)
        self.destiny_checkbox_11.setTristate(False)
        self.destiny_checkbox_10 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_10.setObjectName(u"destiny_checkbox_10")
        self.destiny_checkbox_10.setGeometry(QRect(490, 860, 16, 31))
        self.destiny_checkbox_10.setIconSize(QSize(64, 64))
        self.destiny_checkbox_10.setChecked(False)
        self.destiny_checkbox_10.setTristate(False)
        self.destiny_checkbox_12 = QCheckBox(self.centralwidget)
        self.destiny_checkbox_12.setObjectName(u"destiny_checkbox_12")
        self.destiny_checkbox_12.setGeometry(QRect(550, 860, 16, 31))
        self.destiny_checkbox_12.setIconSize(QSize(64, 64))
        self.destiny_checkbox_12.setChecked(False)
        self.destiny_checkbox_12.setTristate(False)
        self.label_33 = QLabel(self.centralwidget)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(900, 10, 151, 31))
        self.label_33.setFont(font)
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_34 = QLabel(self.centralwidget)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(1080, 10, 151, 31))
        self.label_34.setFont(font)
        self.label_34.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.intrigue_defense_value_text = QLabel(self.centralwidget)
        self.intrigue_defense_value_text.setObjectName(u"intrigue_defense_value_text")
        self.intrigue_defense_value_text.setGeometry(QRect(900, 50, 151, 31))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(True)
        self.intrigue_defense_value_text.setFont(font5)
        self.intrigue_defense_value_text.setToolTipDuration(2)
        self.intrigue_defense_value_text.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.composure_value_text = QLabel(self.centralwidget)
        self.composure_value_text.setObjectName(u"composure_value_text")
        self.composure_value_text.setGeometry(QRect(1080, 50, 151, 31))
        self.composure_value_text.setFont(font5)
#if QT_CONFIG(tooltip)
        self.composure_value_text.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.composure_value_text.setToolTipDuration(2)
        self.composure_value_text.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_35 = QLabel(self.centralwidget)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(730, 10, 151, 31))
        self.label_35.setFont(font)
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.health_value_text = QLabel(self.centralwidget)
        self.health_value_text.setObjectName(u"health_value_text")
        self.health_value_text.setGeometry(QRect(730, 50, 151, 31))
        self.health_value_text.setFont(font5)
        self.health_value_text.setToolTipDuration(2)
        self.health_value_text.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_36 = QLabel(self.centralwidget)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(1260, 10, 151, 31))
        self.label_36.setFont(font)
        self.label_36.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.combat_defense_value_text = QLabel(self.centralwidget)
        self.combat_defense_value_text.setObjectName(u"combat_defense_value_text")
        self.combat_defense_value_text.setGeometry(QRect(1260, 50, 151, 31))
        self.combat_defense_value_text.setFont(font5)
#if QT_CONFIG(tooltip)
        self.combat_defense_value_text.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.combat_defense_value_text.setToolTipDuration(2)
        self.combat_defense_value_text.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_31 = QLabel(self.centralwidget)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(960, 120, 231, 31))
        self.label_31.setFont(font1)
        self.label_31.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_32 = QLabel(self.centralwidget)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(960, 150, 231, 31))
        self.label_32.setFont(font1)
        self.label_32.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_37 = QLabel(self.centralwidget)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(960, 200, 71, 31))
        self.label_37.setFont(font)
        self.label_38 = QLabel(self.centralwidget)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(1070, 200, 81, 31))
        self.label_38.setFont(font)
        self.label_39 = QLabel(self.centralwidget)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(1180, 200, 161, 31))
        self.label_39.setFont(font)
        self.label_40 = QLabel(self.centralwidget)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(790, 200, 71, 31))
        self.label_40.setFont(font)
        self.weapon_name_text_1 = QPlainTextEdit(self.centralwidget)
        self.weapon_name_text_1.setObjectName(u"weapon_name_text_1")
        self.weapon_name_text_1.setGeometry(QRect(790, 230, 151, 31))
        self.weapon_attack_text_1 = QPlainTextEdit(self.centralwidget)
        self.weapon_attack_text_1.setObjectName(u"weapon_attack_text_1")
        self.weapon_attack_text_1.setGeometry(QRect(960, 230, 91, 31))
        self.test_dice_text_2 = QPlainTextEdit(self.centralwidget)
        self.test_dice_text_2.setObjectName(u"test_dice_text_2")
        self.test_dice_text_2.setGeometry(QRect(1070, 230, 91, 31))
        self.weapon_damage_text_1 = QPlainTextEdit(self.centralwidget)
        self.weapon_damage_text_1.setObjectName(u"weapon_damage_text_1")
        self.weapon_damage_text_1.setGeometry(QRect(1180, 230, 231, 31))
        self.test_dice_text_3 = QPlainTextEdit(self.centralwidget)
        self.test_dice_text_3.setObjectName(u"test_dice_text_3")
        self.test_dice_text_3.setGeometry(QRect(1070, 260, 91, 31))
        self.weapon_damage_text_2 = QPlainTextEdit(self.centralwidget)
        self.weapon_damage_text_2.setObjectName(u"weapon_damage_text_2")
        self.weapon_damage_text_2.setGeometry(QRect(1180, 260, 231, 31))
        self.weapon_attack_text_2 = QPlainTextEdit(self.centralwidget)
        self.weapon_attack_text_2.setObjectName(u"weapon_attack_text_2")
        self.weapon_attack_text_2.setGeometry(QRect(960, 260, 91, 31))
        self.weapon_name_text_2 = QPlainTextEdit(self.centralwidget)
        self.weapon_name_text_2.setObjectName(u"weapon_name_text_2")
        self.weapon_name_text_2.setGeometry(QRect(790, 260, 151, 31))
        self.weapon_damage_text_3 = QPlainTextEdit(self.centralwidget)
        self.weapon_damage_text_3.setObjectName(u"weapon_damage_text_3")
        self.weapon_damage_text_3.setGeometry(QRect(1180, 290, 231, 31))
        self.test_dice_text_4 = QPlainTextEdit(self.centralwidget)
        self.test_dice_text_4.setObjectName(u"test_dice_text_4")
        self.test_dice_text_4.setGeometry(QRect(1070, 290, 91, 31))
        self.weapon_attack_text_3 = QPlainTextEdit(self.centralwidget)
        self.weapon_attack_text_3.setObjectName(u"weapon_attack_text_3")
        self.weapon_attack_text_3.setGeometry(QRect(960, 290, 91, 31))
        self.weapon_name_text_3 = QPlainTextEdit(self.centralwidget)
        self.weapon_name_text_3.setObjectName(u"weapon_name_text_3")
        self.weapon_name_text_3.setGeometry(QRect(790, 290, 151, 31))
        self.test_dice_text_5 = QPlainTextEdit(self.centralwidget)
        self.test_dice_text_5.setObjectName(u"test_dice_text_5")
        self.test_dice_text_5.setGeometry(QRect(1070, 320, 91, 31))
        self.weapon_damage_text_4 = QPlainTextEdit(self.centralwidget)
        self.weapon_damage_text_4.setObjectName(u"weapon_damage_text_4")
        self.weapon_damage_text_4.setGeometry(QRect(1180, 320, 231, 31))
        self.weapon_attack_text_4 = QPlainTextEdit(self.centralwidget)
        self.weapon_attack_text_4.setObjectName(u"weapon_attack_text_4")
        self.weapon_attack_text_4.setGeometry(QRect(960, 320, 91, 31))
        self.weapon_name_text_4 = QPlainTextEdit(self.centralwidget)
        self.weapon_name_text_4.setObjectName(u"weapon_name_text_4")
        self.weapon_name_text_4.setGeometry(QRect(790, 320, 151, 31))
        self.label_41 = QLabel(self.centralwidget)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(960, 370, 231, 31))
        self.label_41.setFont(font1)
        self.label_41.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_42 = QLabel(self.centralwidget)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(790, 410, 71, 31))
        self.label_42.setFont(font)
        self.label_43 = QLabel(self.centralwidget)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(960, 410, 141, 31))
        self.label_43.setFont(font)
        self.label_44 = QLabel(self.centralwidget)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(1070, 410, 141, 31))
        self.label_44.setFont(font)
        self.armor_name_text_1 = QPlainTextEdit(self.centralwidget)
        self.armor_name_text_1.setObjectName(u"armor_name_text_1")
        self.armor_name_text_1.setGeometry(QRect(790, 440, 151, 31))
        self.armor_rating_text_1 = QPlainTextEdit(self.centralwidget)
        self.armor_rating_text_1.setObjectName(u"armor_rating_text_1")
        self.armor_rating_text_1.setGeometry(QRect(960, 440, 91, 31))
        self.armor_penalty_text_1 = QPlainTextEdit(self.centralwidget)
        self.armor_penalty_text_1.setObjectName(u"armor_penalty_text_1")
        self.armor_penalty_text_1.setGeometry(QRect(1070, 440, 91, 31))
        self.armor_rating_text_2 = QPlainTextEdit(self.centralwidget)
        self.armor_rating_text_2.setObjectName(u"armor_rating_text_2")
        self.armor_rating_text_2.setGeometry(QRect(960, 470, 91, 31))
        self.armor_name_text_2 = QPlainTextEdit(self.centralwidget)
        self.armor_name_text_2.setObjectName(u"armor_name_text_2")
        self.armor_name_text_2.setGeometry(QRect(790, 470, 151, 31))
        self.armor_rating_text_3 = QPlainTextEdit(self.centralwidget)
        self.armor_rating_text_3.setObjectName(u"armor_rating_text_3")
        self.armor_rating_text_3.setGeometry(QRect(960, 500, 91, 31))
        self.armor_name_text_3 = QPlainTextEdit(self.centralwidget)
        self.armor_name_text_3.setObjectName(u"armor_name_text_3")
        self.armor_name_text_3.setGeometry(QRect(790, 500, 151, 31))
        self.armor_rating_text_4 = QPlainTextEdit(self.centralwidget)
        self.armor_rating_text_4.setObjectName(u"armor_rating_text_4")
        self.armor_rating_text_4.setGeometry(QRect(960, 530, 91, 31))
        self.armor_name_text_4 = QPlainTextEdit(self.centralwidget)
        self.armor_name_text_4.setObjectName(u"armor_name_text_4")
        self.armor_name_text_4.setGeometry(QRect(790, 530, 151, 31))
        self.label_45 = QLabel(self.centralwidget)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(1190, 410, 231, 31))
        self.label_45.setFont(font1)
        self.label_45.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.armor_penalty_text_2 = QPlainTextEdit(self.centralwidget)
        self.armor_penalty_text_2.setObjectName(u"armor_penalty_text_2")
        self.armor_penalty_text_2.setGeometry(QRect(1070, 470, 91, 31))
        self.armor_penalty_text_3 = QPlainTextEdit(self.centralwidget)
        self.armor_penalty_text_3.setObjectName(u"armor_penalty_text_3")
        self.armor_penalty_text_3.setGeometry(QRect(1070, 500, 91, 31))
        self.armor_penalty_text_4 = QPlainTextEdit(self.centralwidget)
        self.armor_penalty_text_4.setObjectName(u"armor_penalty_text_4")
        self.armor_penalty_text_4.setGeometry(QRect(1070, 530, 91, 31))
        self.armor_rating_final_value = QLabel(self.centralwidget)
        self.armor_rating_final_value.setObjectName(u"armor_rating_final_value")
        self.armor_rating_final_value.setGeometry(QRect(1230, 450, 151, 31))
        self.armor_rating_final_value.setFont(font5)
#if QT_CONFIG(tooltip)
        self.armor_rating_final_value.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.armor_rating_final_value.setToolTipDuration(2)
        self.armor_rating_final_value.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_47 = QLabel(self.centralwidget)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(1190, 490, 231, 31))
        self.label_47.setFont(font1)
        self.label_47.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.armor_penalty_final_value = QLabel(self.centralwidget)
        self.armor_penalty_final_value.setObjectName(u"armor_penalty_final_value")
        self.armor_penalty_final_value.setGeometry(QRect(1230, 530, 151, 31))
        self.armor_penalty_final_value.setFont(font5)
#if QT_CONFIG(tooltip)
        self.armor_penalty_final_value.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.armor_penalty_final_value.setToolTipDuration(2)
        self.armor_penalty_final_value.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_46 = QLabel(self.centralwidget)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(60, 890, 131, 31))
        self.label_46.setFont(font)
        self.injuries_checkbox_3 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_3.setObjectName(u"injuries_checkbox_3")
        self.injuries_checkbox_3.setGeometry(QRect(280, 890, 16, 31))
        self.injuries_checkbox_3.setIconSize(QSize(64, 64))
        self.injuries_checkbox_3.setChecked(False)
        self.injuries_checkbox_3.setTristate(False)
        self.injuries_checkbox_5 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_5.setObjectName(u"injuries_checkbox_5")
        self.injuries_checkbox_5.setGeometry(QRect(340, 890, 16, 31))
        self.injuries_checkbox_5.setIconSize(QSize(64, 64))
        self.injuries_checkbox_5.setChecked(False)
        self.injuries_checkbox_5.setTristate(False)
        self.injuries_checkbox_9 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_9.setObjectName(u"injuries_checkbox_9")
        self.injuries_checkbox_9.setGeometry(QRect(460, 890, 16, 31))
        self.injuries_checkbox_9.setIconSize(QSize(64, 64))
        self.injuries_checkbox_9.setChecked(False)
        self.injuries_checkbox_9.setTristate(False)
        self.injuries_checkbox_11 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_11.setObjectName(u"injuries_checkbox_11")
        self.injuries_checkbox_11.setGeometry(QRect(520, 890, 16, 31))
        self.injuries_checkbox_11.setIconSize(QSize(64, 64))
        self.injuries_checkbox_11.setChecked(False)
        self.injuries_checkbox_11.setTristate(False)
        self.injuries_checkbox_2 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_2.setObjectName(u"injuries_checkbox_2")
        self.injuries_checkbox_2.setGeometry(QRect(250, 890, 16, 31))
        self.injuries_checkbox_2.setIconSize(QSize(64, 64))
        self.injuries_checkbox_2.setChecked(False)
        self.injuries_checkbox_2.setTristate(False)
        self.injuries_checkbox_12 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_12.setObjectName(u"injuries_checkbox_12")
        self.injuries_checkbox_12.setGeometry(QRect(550, 890, 16, 31))
        self.injuries_checkbox_12.setIconSize(QSize(64, 64))
        self.injuries_checkbox_12.setChecked(False)
        self.injuries_checkbox_12.setTristate(False)
        self.injuries_checkbox_1 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_1.setObjectName(u"injuries_checkbox_1")
        self.injuries_checkbox_1.setGeometry(QRect(220, 890, 16, 31))
        self.injuries_checkbox_1.setIconSize(QSize(64, 64))
        self.injuries_checkbox_1.setChecked(False)
        self.injuries_checkbox_1.setTristate(False)
        self.injuries_checkbox_7 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_7.setObjectName(u"injuries_checkbox_7")
        self.injuries_checkbox_7.setGeometry(QRect(400, 890, 16, 31))
        self.injuries_checkbox_7.setIconSize(QSize(64, 64))
        self.injuries_checkbox_7.setChecked(False)
        self.injuries_checkbox_7.setTristate(False)
        self.injuries_checkbox_4 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_4.setObjectName(u"injuries_checkbox_4")
        self.injuries_checkbox_4.setGeometry(QRect(310, 890, 16, 31))
        self.injuries_checkbox_4.setIconSize(QSize(64, 64))
        self.injuries_checkbox_4.setChecked(False)
        self.injuries_checkbox_4.setTristate(False)
        self.injuries_checkbox_10 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_10.setObjectName(u"injuries_checkbox_10")
        self.injuries_checkbox_10.setGeometry(QRect(490, 890, 16, 31))
        self.injuries_checkbox_10.setIconSize(QSize(64, 64))
        self.injuries_checkbox_10.setChecked(False)
        self.injuries_checkbox_10.setTristate(False)
        self.injuries_checkbox_6 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_6.setObjectName(u"injuries_checkbox_6")
        self.injuries_checkbox_6.setGeometry(QRect(370, 890, 16, 31))
        self.injuries_checkbox_6.setIconSize(QSize(64, 64))
        self.injuries_checkbox_6.setChecked(False)
        self.injuries_checkbox_6.setTristate(False)
        self.injuries_checkbox_8 = QCheckBox(self.centralwidget)
        self.injuries_checkbox_8.setObjectName(u"injuries_checkbox_8")
        self.injuries_checkbox_8.setGeometry(QRect(430, 890, 16, 31))
        self.injuries_checkbox_8.setIconSize(QSize(64, 64))
        self.injuries_checkbox_8.setChecked(False)
        self.injuries_checkbox_8.setTristate(False)
        self.label_48 = QLabel(self.centralwidget)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(970, 580, 231, 31))
        self.label_48.setFont(font1)
        self.label_48.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_49 = QLabel(self.centralwidget)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(820, 610, 71, 31))
        self.label_49.setFont(font)
        self.label_49.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_50 = QLabel(self.centralwidget)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(910, 610, 71, 31))
        self.label_50.setFont(font)
        self.label_50.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_51 = QLabel(self.centralwidget)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(1000, 610, 71, 31))
        self.label_51.setFont(font)
        self.label_51.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_52 = QLabel(self.centralwidget)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(1090, 610, 71, 31))
        self.label_52.setFont(font)
        self.label_52.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_53 = QLabel(self.centralwidget)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(1180, 610, 71, 31))
        self.label_53.setFont(font)
        self.label_53.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_54 = QLabel(self.centralwidget)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(1270, 610, 71, 31))
        self.label_54.setFont(font)
        self.label_54.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.gd_value_text = QPlainTextEdit(self.centralwidget)
        self.gd_value_text.setObjectName(u"gd_value_text")
        self.gd_value_text.setGeometry(QRect(820, 640, 71, 31))
        self.sm_value_text = QPlainTextEdit(self.centralwidget)
        self.sm_value_text.setObjectName(u"sm_value_text")
        self.sm_value_text.setGeometry(QRect(910, 640, 71, 31))
        self.ss_value_text = QPlainTextEdit(self.centralwidget)
        self.ss_value_text.setObjectName(u"ss_value_text")
        self.ss_value_text.setGeometry(QRect(1000, 640, 71, 31))
        self.cs_value_text = QPlainTextEdit(self.centralwidget)
        self.cs_value_text.setObjectName(u"cs_value_text")
        self.cs_value_text.setGeometry(QRect(1090, 640, 71, 31))
        self.cg_value_text = QPlainTextEdit(self.centralwidget)
        self.cg_value_text.setObjectName(u"cg_value_text")
        self.cg_value_text.setGeometry(QRect(1180, 640, 71, 31))
        self.cp_value_text = QPlainTextEdit(self.centralwidget)
        self.cp_value_text.setObjectName(u"cp_value_text")
        self.cp_value_text.setGeometry(QRect(1270, 640, 71, 31))
        self.import_sheet_button = QPushButton(self.centralwidget)
        self.import_sheet_button.setObjectName(u"import_sheet_button")
        self.import_sheet_button.setGeometry(QRect(1230, 840, 161, 51))
        self.import_sheet_button.setFont(font)
        self.export_sheet_button = QPushButton(self.centralwidget)
        self.export_sheet_button.setObjectName(u"export_sheet_button")
        self.export_sheet_button.setGeometry(QRect(1230, 780, 161, 51))
        self.export_sheet_button.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1439, 21))
        self.menuASOIAF_Character_Sheet_Editor = QMenu(self.menubar)
        self.menuASOIAF_Character_Sheet_Editor.setObjectName(u"menuASOIAF_Character_Sheet_Editor")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuASOIAF_Character_Sheet_Editor.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"AGE", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"GENDER", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"HOUSE", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"ABILITIES", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RATING", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"SPECIALTIES", None))
        self.rating_text_1.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Agility", None))
        self.specialties_text_1.setPlainText(QCoreApplication.translate("MainWindow", u"Separate specialties by a ,", None))
        self.specialties_text_2.setPlainText("")
        self.rating_text_2.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Animal Handling", None))
        self.specialties_text_3.setPlainText("")
        self.rating_text_3.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_4.setPlainText("")
        self.rating_text_4.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Athletics", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Awareness", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Cunning", None))
        self.rating_text_5.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_5.setPlainText("")
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Endurance", None))
        self.rating_text_6.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_6.setPlainText("")
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Fighting", None))
        self.rating_text_7.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_7.setPlainText("")
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Healing", None))
        self.rating_text_8.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_8.setPlainText("")
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Language", None))
        self.rating_text_9.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_9.setPlainText("")
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Knowledge", None))
        self.rating_text_10.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_10.setPlainText("")
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Marksmanship", None))
        self.rating_text_11.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_11.setPlainText("")
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Persuasion", None))
        self.rating_text_12.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_12.setPlainText("")
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.rating_text_13.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_13.setPlainText("")
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Stealth", None))
        self.rating_text_14.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_14.setPlainText("")
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Survival", None))
        self.rating_text_15.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_15.setPlainText("")
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Thievery", None))
        self.rating_text_16.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_16.setPlainText("")
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Warfare", None))
        self.rating_text_17.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_17.setPlainText("")
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Will", None))
        self.rating_text_18.setPlainText(QCoreApplication.translate("MainWindow", u"2", None))
        self.specialties_text_18.setPlainText("")
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"BONUS DICE", None))
        self.bonus_dice_text_1.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_2.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_3.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_4.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_5.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_6.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_7.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_8.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_9.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_10.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_11.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_12.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_13.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_14.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_15.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_16.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_17.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.bonus_dice_text_18.setPlainText(QCoreApplication.translate("MainWindow", u"2\n"
"\n"
"", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"TOTAL DICE", None))
        self.total_dice_1.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_3.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_4.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_5.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_6.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_7.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_8.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_9.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_10.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_11.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_12.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_13.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_14.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_15.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_16.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_17.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.total_dice_18.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.qualities_text.setPlainText("")
        self.destiny_checkbox_1.setText("")
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"QUALITIES", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"DESTINY POINTS", None))
        self.destiny_checkbox_2.setText("")
        self.destiny_checkbox_4.setText("")
        self.destiny_checkbox_3.setText("")
        self.destiny_checkbox_5.setText("")
        self.destiny_checkbox_6.setText("")
        self.destiny_checkbox_8.setText("")
        self.destiny_checkbox_7.setText("")
        self.destiny_checkbox_9.setText("")
        self.destiny_checkbox_11.setText("")
        self.destiny_checkbox_10.setText("")
        self.destiny_checkbox_12.setText("")
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"INTRIGUE DEFENSE", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"COMPOSURE", None))
#if QT_CONFIG(tooltip)
        self.intrigue_defense_value_text.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.intrigue_defense_value_text.setText(QCoreApplication.translate("MainWindow", u"VALUE", None))
        self.composure_value_text.setText(QCoreApplication.translate("MainWindow", u"VALUE", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"HEALTH", None))
#if QT_CONFIG(tooltip)
        self.health_value_text.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.health_value_text.setText(QCoreApplication.translate("MainWindow", u"CURRENT / MAX", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"COMBAT DEFENSE", None))
        self.combat_defense_value_text.setText(QCoreApplication.translate("MainWindow", u"VALUE", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"EQUIPMENT", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"WEAPONS", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"ATTACK", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"TEST DICE", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"WEAPON DAMAGE", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.weapon_name_text_1.setPlainText("")
        self.weapon_attack_text_1.setPlainText("")
        self.test_dice_text_2.setPlainText("")
        self.weapon_damage_text_1.setPlainText("")
        self.test_dice_text_3.setPlainText("")
        self.weapon_damage_text_2.setPlainText("")
        self.weapon_attack_text_2.setPlainText("")
        self.weapon_name_text_2.setPlainText("")
        self.weapon_damage_text_3.setPlainText("")
        self.test_dice_text_4.setPlainText("")
        self.weapon_attack_text_3.setPlainText("")
        self.weapon_name_text_3.setPlainText("")
        self.test_dice_text_5.setPlainText("")
        self.weapon_damage_text_4.setPlainText("")
        self.weapon_attack_text_4.setPlainText("")
        self.weapon_name_text_4.setPlainText("")
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"ARMOR", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"NAME", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"RATING", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"PENALTY", None))
        self.armor_name_text_1.setPlainText("")
        self.armor_rating_text_1.setPlainText("")
        self.armor_penalty_text_1.setPlainText("")
        self.armor_rating_text_2.setPlainText("")
        self.armor_name_text_2.setPlainText("")
        self.armor_rating_text_3.setPlainText("")
        self.armor_name_text_3.setPlainText("")
        self.armor_rating_text_4.setPlainText("")
        self.armor_name_text_4.setPlainText("")
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"ARMOR RATING", None))
        self.armor_penalty_text_2.setPlainText("")
        self.armor_penalty_text_3.setPlainText("")
        self.armor_penalty_text_4.setPlainText("")
        self.armor_rating_final_value.setText(QCoreApplication.translate("MainWindow", u"VALUE", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"ARMOR PENALTY", None))
        self.armor_penalty_final_value.setText(QCoreApplication.translate("MainWindow", u"VALUE", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"INJURIES", None))
        self.injuries_checkbox_3.setText("")
        self.injuries_checkbox_5.setText("")
        self.injuries_checkbox_9.setText("")
        self.injuries_checkbox_11.setText("")
        self.injuries_checkbox_2.setText("")
        self.injuries_checkbox_12.setText("")
        self.injuries_checkbox_1.setText("")
        self.injuries_checkbox_7.setText("")
        self.injuries_checkbox_4.setText("")
        self.injuries_checkbox_10.setText("")
        self.injuries_checkbox_6.setText("")
        self.injuries_checkbox_8.setText("")
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"CURRENCY", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"GD", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"SM", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"SS", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"CS", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"CG", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"CP", None))
        self.gd_value_text.setPlainText("")
        self.sm_value_text.setPlainText("")
        self.ss_value_text.setPlainText("")
        self.cs_value_text.setPlainText("")
        self.cg_value_text.setPlainText("")
        self.cp_value_text.setPlainText("")
        self.import_sheet_button.setText(QCoreApplication.translate("MainWindow", u"IMPORT CHARACTER\n"
"SHEET", None))
        self.export_sheet_button.setText(QCoreApplication.translate("MainWindow", u"EXPORT CHARACTER\n"
"SHEET", None))
        self.menuASOIAF_Character_Sheet_Editor.setTitle(QCoreApplication.translate("MainWindow", u"ASOIAF Character Sheet Editor", None))
    # retranslateUi

